#!/usr/bin/env python3
"""Add protocol/block context to NMC optical event cycles.

This uses the compact event/echem cycle table generated by
tier1_event_echem_coupling.py and asks whether abrupt optical events occur near
protocol block boundaries or in unusually short/long cycle-frame regimes.
"""

import argparse
import json
import os
from typing import List

import numpy as np
import pandas as pd
from scipy.stats import mannwhitneyu, spearmanr


def add_block_context(df: pd.DataFrame) -> pd.DataFrame:
    out = df.sort_values("cycleNo").reset_index(drop=True).copy()
    block = out.get("block_mode", pd.Series([""] * len(out))).fillna("").astype(str)
    changed = block.ne(block.shift(1)).fillna(True)
    out["protocol_block_segment"] = changed.cumsum().astype(int)

    seg_rows = []
    for seg, g in out.groupby("protocol_block_segment", sort=True):
        cycles = g["cycleNo"].to_numpy(dtype=float)
        if cycles.size == 0:
            continue
        seg_rows.append({
            "protocol_block_segment": int(seg),
            "block_mode": str(g["block_mode"].iloc[0]) if "block_mode" in g else "",
            "block_start_cycle": float(np.nanmin(cycles)),
            "block_end_cycle": float(np.nanmax(cycles)),
            "block_n_cycles": int(len(g)),
        })
    seg_df = pd.DataFrame(seg_rows)
    out = out.merge(seg_df, on="protocol_block_segment", how="left", suffixes=("", "_segment"))
    out["cycles_from_block_start"] = out["cycleNo"] - out["block_start_cycle"]
    out["cycles_to_block_end"] = out["block_end_cycle"] - out["cycleNo"]
    denom = (out["block_end_cycle"] - out["block_start_cycle"]).replace(0, np.nan)
    out["block_fraction_elapsed"] = (out["cycleNo"] - out["block_start_cycle"]) / denom
    out["near_block_boundary_10cycles"] = ((out["cycles_from_block_start"] <= 10) | (out["cycles_to_block_end"] <= 10)).astype(int)
    return out


def compare(df: pd.DataFrame, label: str, features: List[str]) -> pd.DataFrame:
    rows = []
    y = df[label].fillna(0).astype(int)
    for feat in features:
        x = pd.to_numeric(df.get(feat), errors="coerce")
        a = x[(y == 1) & x.notna()].to_numpy(dtype=float)
        b = x[(y == 0) & x.notna()].to_numpy(dtype=float)
        if len(a) < 1 or len(b) < 3:
            continue
        try:
            _stat, p = mannwhitneyu(a, b, alternative="two-sided")
        except Exception:
            p = np.nan
        rho = np.nan
        rho_p = np.nan
        yy = y[x.notna()].to_numpy(dtype=float)
        xx = x[x.notna()].to_numpy(dtype=float)
        if len(xx) >= 5 and np.nanstd(xx) > 0:
            rho, rho_p = spearmanr(xx, yy)
        rows.append({
            "label": label,
            "feature": feat,
            "event_mean": float(np.mean(a)),
            "non_event_mean": float(np.mean(b)),
            "event_median": float(np.median(a)),
            "non_event_median": float(np.median(b)),
            "event_n": int(len(a)),
            "non_event_n": int(len(b)),
            "mannwhitney_p": float(p) if np.isfinite(p) else np.nan,
            "spearman_rho": float(rho) if np.isfinite(rho) else np.nan,
            "spearman_p": float(rho_p) if np.isfinite(rho_p) else np.nan,
        })
    return pd.DataFrame(rows).sort_values(["label", "mannwhitney_p", "feature"], na_position="last") if rows else pd.DataFrame()


def boundary_enrichment(df: pd.DataFrame, label: str) -> dict:
    y = df[label].fillna(0).astype(int)
    near = df["near_block_boundary_10cycles"].fillna(0).astype(int)
    event_rate_near = float(y[near == 1].mean()) if (near == 1).any() else np.nan
    event_rate_far = float(y[near == 0].mean()) if (near == 0).any() else np.nan
    return {
        "label": label,
        "n_near_boundary": int((near == 1).sum()),
        "n_far_boundary": int((near == 0).sum()),
        "event_rate_near_boundary": event_rate_near,
        "event_rate_far_boundary": event_rate_far,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--event-echem-dir", default="/scratch/u6hp/nsagar.u6hp/Alek_Jiho/derived/event_echem_coupling")
    parser.add_argument("--out-dir", default="/scratch/u6hp/nsagar.u6hp/Alek_Jiho/derived/event_protocol_context")
    args = parser.parse_args()

    in_path = os.path.join(args.event_echem_dir, "event_echem_cycle_table.csv")
    if not os.path.exists(in_path):
        raise SystemExit("event_echem_cycle_table.csv not found; run tier1_event_echem_coupling.py first")
    df = pd.read_csv(in_path)
    df["cycleNo"] = pd.to_numeric(df["cycleNo"], errors="coerce")
    df = df.dropna(subset=["cycleNo"]).sort_values("cycleNo")
    enriched = add_block_context(df)

    os.makedirs(args.out_dir, exist_ok=True)
    enriched_path = os.path.join(args.out_dir, "event_protocol_context_table.csv")
    enriched.to_csv(enriched_path, index=False)

    features = [
        "n_frames", "n_frames_percentile", "cycles_from_block_start", "cycles_to_block_end",
        "block_fraction_elapsed", "block_n_cycles", "near_block_boundary_10cycles",
        "V_mean", "I_mean_mA", "V_mean_delta", "I_mean_delta",
    ]
    features = [f for f in features if f in enriched.columns]
    tests = pd.concat([
        compare(enriched, "any_event", features),
        compare(enriched, "synchronized_event", features),
    ], ignore_index=True)
    tests_path = os.path.join(args.out_dir, "protocol_context_feature_tests.csv")
    tests.to_csv(tests_path, index=False)

    event_cycles = enriched[enriched["any_event"] == 1].copy()
    sync_cycles = enriched[enriched["synchronized_event"] == 1].copy()
    summary = {
        "input_table": in_path,
        "n_cycles": int(len(enriched)),
        "n_protocol_block_segments": int(enriched["protocol_block_segment"].nunique()),
        "n_any_event_cycles": int(enriched["any_event"].sum()),
        "n_synchronized_event_cycles": int(enriched["synchronized_event"].sum()),
        "boundary_enrichment": [boundary_enrichment(enriched, "any_event"), boundary_enrichment(enriched, "synchronized_event")],
        "event_cycles": event_cycles[["cycleNo", "n_particles_event", "particles", "block_mode", "cycles_from_block_start", "cycles_to_block_end", "block_fraction_elapsed", "n_frames_percentile"]].to_dict(orient="records"),
        "synchronized_event_cycles": sync_cycles[["cycleNo", "n_particles_event", "particles", "block_mode", "cycles_from_block_start", "cycles_to_block_end", "block_fraction_elapsed", "n_frames_percentile"]].to_dict(orient="records"),
        "top_tests": tests.head(12).to_dict(orient="records") if not tests.empty else [],
    }
    summary_path = os.path.join(args.out_dir, "event_protocol_context_summary.json")
    with open(summary_path, "w") as f:
        json.dump(summary, f, indent=2, sort_keys=True)

    readme_path = os.path.join(args.out_dir, "README.md")
    lines = [
        "# NMC Event Protocol Context",
        "",
        "Adds protocol block-position context to abrupt optical event cycles.",
        "",
        "## Summary",
        "",
        f"- Cycles analyzed: {summary['n_cycles']}",
        f"- Protocol block segments in matched table: {summary['n_protocol_block_segments']}",
        f"- Any-event cycles: {summary['n_any_event_cycles']}",
        f"- Synchronized-event cycles: {summary['n_synchronized_event_cycles']}",
        "",
        "## Event Cycles",
        "",
        "| cycleNo | n_particles_event | block_mode | from_start | to_end | block_fraction_elapsed | n_frames_percentile |",
        "|---:|---:|---|---:|---:|---:|---:|",
    ]
    for _, row in event_cycles.iterrows():
        lines.append("| {cycleNo:.1f} | {n} | `{block}` | {fs} | {te} | {frac} | {fp} |".format(
            cycleNo=float(row["cycleNo"]),
            n=int(row["n_particles_event"]),
            block=row.get("block_mode", ""),
            fs="" if pd.isna(row.get("cycles_from_block_start", np.nan)) else f"{float(row['cycles_from_block_start']):.1f}",
            te="" if pd.isna(row.get("cycles_to_block_end", np.nan)) else f"{float(row['cycles_to_block_end']):.1f}",
            frac="" if pd.isna(row.get("block_fraction_elapsed", np.nan)) else f"{float(row['block_fraction_elapsed']):.3f}",
            fp="" if pd.isna(row.get("n_frames_percentile", np.nan)) else f"{float(row['n_frames_percentile']):.3f}",
        ))
    lines.extend(["", "## Strongest Context Differences", "", "| label | feature | event_mean | non_event_mean | p |", "|---|---|---:|---:|---:|"])
    for _, row in tests.head(10).iterrows():
        lines.append("| {label} | `{feature}` | {em:.4g} | {nm:.4g} | {p:.4g} |".format(
            label=row["label"], feature=row["feature"], em=float(row["event_mean"]), nm=float(row["non_event_mean"]), p=float(row["mannwhitney_p"])
        ))
    lines.extend(["", "## Interpretation Guardrail", "", "This protocol-context pass is exploratory. Event counts are small, and protocol segment definitions are inferred from dominant echem block labels per cycle.", ""])
    with open(readme_path, "w") as f:
        f.write("\n".join(lines))

    for p in [enriched_path, tests_path, summary_path, readme_path]:
        print(f"Saved: {p}")
    print(json.dumps(summary, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
